jsSrcDir: src/js/
jsDir: dist/js/
cssSrcDir: src/css/
cssDir: dist/css/
vendorDir: vendor/
vendorMinJs: includes.min.js
vendorMinCss: includes.min.css
appMinJs: resume.min.js
appMinCss: resume.min.css
appCss: resume.css
appJs: resume.js
minJs: "*.min.js"
minCss: "*.min.css"
